import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "TikTok",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary">
        <Navbar />
        <div className="flex mx-7">
          <Sidebar />
          <div className="ms-[200px] w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
